owner: ForceManager
repo: status

sites:
  - name: API
    url: $URL_API
  - name: APP
    url: $URL_APP
  - name: BACKEND
    url: $URL_BACKEND

status-website:
  cname: status.forcemanager.com
  theme: light
  name: ForceManager Status
  logoUrl: https://www.forcemanager.com/wp-content/uploads/positive.svg
  faviconSvg: https://www.forcemanager.com/wp-content/themes/forcemanager/images/favicon.svg  
  introTitle: "Status ForceManager Services"
  navbar:
    - title: Status
      href: /
    - title: ForceManager
      href: https://www.forcemanager.com/

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"
