owner: ForceManager
repo: status

sites:
  - name: API
    url: https://api.forcemanager.net/healthcheck
  - name: APP
    url: https://app.forcemanager.net
  - name: BE-PRO
    url: https://be-pro.forcemanager.net/healthcheck.ashx

status-website:
  cname: status.forcemanager.com
  theme: light
  name: ForceManager Status
  logoUrl: https://www.forcemanager.com/wp-content/uploads/positive.svg
  introTitle: "Status of ForceManager Services"
  navbar:
    - title: Status
      href: /
    - title: ForceManager
      href: https://www.forcemanager.com/
