owner: ForceManager
repo: status

sites:
  - name: API
    url: $URL_API
  - name: APP
    url: $URL_APP
  - name: BACKEND
    url: $URL_BACKEND

status-website:
  cname: status.forcemanager.com
  theme: light
  name: ForceManager Status
  logoUrl: https://www.forcemanager.com/wp-content/uploads/positive.svg
  introTitle: "Status of ForceManager Services"
  navbar:
    - title: Status
      href: /
    - title: ForceManager
      href: https://www.forcemanager.com/
